name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Run Streamlit app tests
      uses: streamlit/streamlit-app-action@v0.0.3
      with:
        app-path: streamlit_app.py

    - name: Run linting
      run: |
        pip install black flake8
        black --check .
        flake8 .
